name: Check Jira key in PR title exists and is valid

# Runs when opening or changing a PR
on: 
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main
      - 'release/**'
    
jobs:
  # This workflow contains a single job called "check-jira"
  check-jira:
    # Run on Ubuntu (Linux)
    runs-on: ubuntu-latest

    steps:
      - uses: arup-group/action-pr-title-jira-check@main
        if: startsWith( github.event.pull_request.head.ref, 'release') == false
        with:
          prTitle: '${{ github.event.pull_request.title }}'
          jiraSecret: '${{ secrets.JIRA_PASSWORD }}'
          statusCategory: 'In Progress'
          jiraUsername: 'automation@arup.com'
